"""
Django settings for mythanzi project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from importlib.util import find_spec
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


RUNNING_IN_DOCKER = env_bool('RUNNING_IN_DOCKER') or Path('/.dockerenv').exists()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-set-secret-key-in-env'
    else:
        raise RuntimeError('SECRET_KEY must be set when DEBUG is false.')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'api.apps.ApiConfig',
    'users.apps.UsersConfig',
    'locations',
    'chatbot',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if RUNNING_IN_DOCKER or find_spec('whitenoise') is not None:
    # Must be directly below SecurityMiddleware when available.
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = 'mythanzi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mythanzi.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'users.backends.TemporaryPasswordBackend',
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Read Postgres connection values from environment.
POSTGRES_DB = os.environ.get('POSTGRES_DB', 'mythanzi')
POSTGRES_USER = os.environ.get('POSTGRES_USER', 'postgres')
POSTGRES_PASSWORD = os.environ.get('POSTGRES_PASSWORD', '')
POSTGRES_HOST = os.environ.get('POSTGRES_HOST', 'db' if RUNNING_IN_DOCKER else '127.0.0.1')
POSTGRES_LOCAL_PORT = os.environ.get('POSTGRES_LOCAL_PORT', '55462')
POSTGRES_PORT = os.environ.get('POSTGRES_PORT', '5432' if RUNNING_IN_DOCKER else POSTGRES_LOCAL_PORT)

# The Compose service name `db` only resolves inside Docker. When running Django
# directly on the host, use the database port published by docker-compose.yml.
if not RUNNING_IN_DOCKER and POSTGRES_HOST == 'db':
    POSTGRES_HOST = '127.0.0.1'
    if POSTGRES_PORT == '5432':
        POSTGRES_PORT = POSTGRES_LOCAL_PORT

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'HOST': POSTGRES_HOST,
        'PORT': POSTGRES_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lusaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# If you store custom assets in a top-level 'static' folder
STATIC_DIR = BASE_DIR / 'static'
STATICFILES_DIRS = [STATIC_DIR] if STATIC_DIR.exists() else []

FRONTEND_DIST_DIR = BASE_DIR / 'static' / 'vue'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 50,
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/users/dashboard/'

# Use the standard Django SMTP backend for production
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)

# Google SMTP Server details
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Security settings (Gmail uses TLS over port 587)
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'

# The email address that appears in the "From" field
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

ZAMTEL_SMS_URL = os.environ.get('ZAMTEL_SMS_URL', '')
ZAMTEL_SMS_API_KEY = os.environ.get('ZAMTEL_SMS_API_KEY', '')
ZAMTEL_SMS_SENDER_ID = os.environ.get('ZAMTEL_SMS_SENDER_ID', 'MyThanzi')
ZAMTEL_SMS_TIMEOUT_SECONDS = int(os.environ.get('ZAMTEL_SMS_TIMEOUT_SECONDS', '10'))

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_CHATBOT_MODEL = os.environ.get('OPENAI_CHATBOT_MODEL', 'gpt-5-mini')

OSRM_BASE_URL = (
    os.environ.get('OSRM_BASE_URL')
    or os.environ.get('OSRM_URL')
    or ('http://osrm-zambia:5000' if RUNNING_IN_DOCKER else 'http://127.0.0.1:5000')
).rstrip('/')
if not RUNNING_IN_DOCKER and '://osrm-zambia:' in OSRM_BASE_URL:
    OSRM_BASE_URL = OSRM_BASE_URL.replace('://osrm-zambia:', '://127.0.0.1:')
OSRM_ROUTE_PROFILE = os.environ.get('OSRM_ROUTE_PROFILE', 'driving')
OSRM_DISTANCE_CANDIDATE_LIMIT = int(os.environ.get('OSRM_DISTANCE_CANDIDATE_LIMIT', '99'))

HAPI_FHIR_BASE_URL = os.environ.get(
    'HAPI_FHIR_BASE_URL',
    'http://hapi-fhir:8080/fhir' if RUNNING_IN_DOCKER else 'http://127.0.0.1:7201/fhir',
).rstrip('/')
HAPI_FHIR_SYNC_ENABLED = env_bool('HAPI_FHIR_SYNC_ENABLED', True)
HAPI_FHIR_TIMEOUT_SECONDS = int(os.environ.get('HAPI_FHIR_TIMEOUT_SECONDS', '5'))

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
