# services:
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: mythanzi
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: replace-this-postgres-password
#     ports:
#       - "55432:5432"
#     volumes:
#       - f69c70051682fcdc999e41b60fdf8d02284b6439ded61080028991c9309797e6:/var/lib/postgresql/data

#   web:
#     build: .
#     command: gunicorn --bind 0.0.0.0:8000 mythanzi.wsgi
#     ports:
#       - "7000:8000"
#     env_file:
#       - .env 
#     depends_on:
#       - db

# volumes:
#   f69c70051682fcdc999e41b60fdf8d02284b6439ded61080028991c9309797e6:
#     external: true
