upstream django_app {
    server web:8000; # Connects directly to the web service name
}

server {
    listen 80;
    listen [::]:80;
    server_name _; # Accepts any connection IP (like 127.0.0.1 or 172.20.10.7)

    # Automatically redirect all unencrypted HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _; # Accepts any connection IP (like 127.0.0.1 or 172.20.10.7)

    ssl_certificate /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # CRITICAL FIX: Send all root web traffic straight to Gunicorn
    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    # Serve static assets directly through Nginx
    location /static/ {
        alias /app/staticfiles/;
    }
}
