# Generated by Django 6.0.5 on 2026-06-01 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0002_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_purpose', models.CharField(choices=[('clinical_review', 'Clinical Review (Checkup)'), ('lab_collection', 'Lab Collection'), ('medication_refill', 'Medication Refill'), ('follow_up', 'Follow-up Visit')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed')], default='upcoming', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='locations.district')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='locations.facility')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='locations.province')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
