# Generated by Django 6.0.5 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temporary_password_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
