# Generated by Django 6.0.5 on 2026-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_temporary_password_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme_color',
            field=models.CharField(choices=[('slate', 'Slate'), ('teal', 'Teal'), ('indigo', 'Indigo'), ('rose', 'Rose'), ('amber', 'Amber'), ('sky', 'Sky'), ('light', 'Light'), ('dark', 'Dark')], default='slate', max_length=20),
        ),
    ]
