# Generated by Django 5.0.3 on 2026-06-23 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_service_facility_services'),
        ('users', '0015_clinicfeedbacksubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_based_management', models.BooleanField(default=True)),
                ('consent_to_follow_up', models.BooleanField(default=False)),
                ('consent_to_sms', models.BooleanField(default=False)),
                ('consent_to_whatsapp', models.BooleanField(default=False)),
                ('share_with_facility', models.BooleanField(default=False)),
                ('privacy_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_consent', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_client_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__username'],
            },
        ),
        migrations.CreateModel(
            name='ClientJourneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('contact', 'Contact'), ('risk_assessment', 'Risk assessment'), ('referral', 'Referral'), ('hivst', 'HIVST'), ('prep_len_initiation', 'PrEP/LEN initiation'), ('follow_up', 'Follow-up'), ('continuation', 'Continuation')], max_length=40)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('referred', 'Referred'), ('continued', 'Continued'), ('stopped', 'Stopped')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_events', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_journey_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientLocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_notes', models.TextField(blank=True)),
                ('preferred_visit_time', models.CharField(blank=True, max_length=120)),
                ('mobiliser_zone', models.CharField(blank=True, max_length=120)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('phone', 'Phone call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('clinic', 'Clinic visit'), ('mobiliser', 'Mobiliser follow-up')], max_length=20)),
                ('outreach_follow_up_details', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_locator', to=settings.AUTH_USER_MODEL)),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_locators', to='locations.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_client_locators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__username'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('missed_appointment', 'Missed appointment'), ('tracing', 'Tracing'), ('re_engagement', 'Re-engagement'), ('referral_confirmation', 'Referral confirmation'), ('other', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_up_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_follow_up_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=40)),
                ('receiving_hub', models.CharField(max_length=180)),
                ('confirmation_status', models.CharField(choices=[('issued', 'Issued'), ('received', 'Received by hub'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='issued', max_length=30)),
                ('initiation_outcome', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('not_eligible', 'Not eligible'), ('declined', 'Declined'), ('lost_to_follow_up', 'Lost to follow-up')], default='pending', max_length=30)),
                ('referred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-referred_on', '-created_at'],
            },
        ),
    ]
