# Generated by Django 5.0.3 on 2026-06-24 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_service_facility_services'),
        ('users', '0017_populationgroup_userprofile_population_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('guidance', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('client_code', models.CharField(blank=True, max_length=80)),
                ('service_point_type', models.CharField(choices=[('hub', 'Hub'), ('spoke', 'Spoke'), ('other', 'Other service point')], max_length=20)),
                ('waiting_time_rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('staff_attitude_rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('privacy_respected', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Not sure')], max_length=10)),
                ('information_clarity_score', models.PositiveSmallIntegerField(choices=[(1, '1 - Very poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('len_questions_understood', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Not sure')], max_length=10)),
                ('net_promoter_score', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('dashboard_ready', models.BooleanField(default=True)),
                ('population_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews', to='users.populationgroup')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews', to='locations.facility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('guidance', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('submission_channel', models.CharField(choices=[('in_app', 'In-app form'), ('qr_box', 'QR suggestion box'), ('verbal_log', 'Verbal log'), ('peer_navigator', 'Peer navigator entry')], default='in_app', max_length=30)),
                ('category', models.CharField(choices=[('service', 'Service'), ('staff', 'Staff'), ('access', 'Access'), ('stigma', 'Stigma'), ('discrimination', 'Discrimination'), ('quality', 'Programme quality'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('complaint_details', models.TextField()),
                ('response_provided', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('assigned', 'Assigned'), ('under_review', 'Under review'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='received', max_length=30)),
                ('escalation_target', models.CharField(blank=True, choices=[('', 'Not escalated'), ('programme_manager', 'Programme Manager'), ('psc', 'PSC'), ('governance_structure', 'Other governance structure')], max_length=40)),
                ('sla_deadline', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievance_cases', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievance_cases', to='locations.district')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'sla_deadline', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SafeguardingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('guidance', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('incident_type', models.CharField(choices=[('abuse', 'Abuse or exploitation'), ('harassment', 'Harassment'), ('coercion', 'Coercion or pressure'), ('privacy_breach', 'Privacy breach'), ('unsafe_service', 'Unsafe service environment'), ('other', 'Other concern')], max_length=40)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('involved_parties', models.TextField(blank=True)),
                ('incident_details', models.TextField()),
                ('confidentiality_locked', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='received', max_length=30)),
                ('sla_deadline', models.DateField(blank=True, null=True)),
                ('risk_trigger_flag', models.BooleanField(default=False)),
                ('cab_oversight_ready', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focal_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_safeguarding_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'sla_deadline', '-submitted_at'],
            },
        ),
    ]
