# Generated by Django 5.0.3 on 2026-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_referral_tracking_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationgroup',
            name='sex_eligibility',
            field=models.CharField(choices=[('all', 'All sexes'), ('female', 'Female only'), ('male', 'Male only')], default='all', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other / Not specified')], max_length=12, null=True),
        ),
    ]
