# Generated by Django 5.0.3 on 2026-06-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_populationgroup_sex_eligibility_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeguardingcase',
            name='incident_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='safeguardingcase',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('abuse', 'Abuse or exploitation'), ('harassment', 'Harassment'), ('coercion', 'Coercion or pressure'), ('privacy_breach', 'Privacy breach'), ('unsafe_service', 'Unsafe service environment'), ('other', 'Other concern')], max_length=40),
        ),
        migrations.AlterField(
            model_name='safeguardingcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='received', max_length=30),
        ),
    ]
