# Generated by Django 5.0.3 on 2026-06-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_apply_services_to_hub_spoke_facilities'),
        ('users', '0021_alter_safeguardingcase_incident_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safeguardingcase',
            name='location_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safeguarding_cases', to='locations.facility'),
        ),
    ]
