# Generated by Django 5.0.3 on 2026-06-25 23:12

from django.db import migrations, models


DEFAULT_NOTIFICATION_TYPE_SETTINGS = [
    {
        'key': 'medication_dose',
        'name': 'Medication Dose',
        'description': 'Daily medicine, PrEP, LEN, or other prevention product reminders.',
        'cadence': 'daily',
        'channel': 'portal',
        'timing': '08:00',
    },
    {
        'key': 'appointment',
        'name': 'Appointment',
        'description': 'Upcoming clinic, review, initiation, injection, or refill visits.',
        'cadence': 'before_event',
        'channel': 'portal_email',
        'timing': '24h',
    },
    {
        'key': 'medication_refill',
        'name': 'Medication Refill',
        'description': 'Refill collection and stock continuity reminders.',
        'cadence': 'before_event',
        'channel': 'portal',
        'timing': '72h',
    },
    {
        'key': 'lab_collection',
        'name': 'Lab Collection',
        'description': 'Lab sample collection and result follow-up reminders.',
        'cadence': 'before_event',
        'channel': 'portal',
        'timing': '24h',
    },
    {
        'key': 'referral_follow_up',
        'name': 'Referral Follow-Up',
        'description': 'Reminders to confirm attendance, linkage, and referral outcomes.',
        'cadence': 'after_event',
        'channel': 'portal',
        'timing': '48h',
    },
    {
        'key': 'side_effect_check_in',
        'name': 'Side-Effect Check-In',
        'description': 'Safety and tolerability check-ins after initiation or product changes.',
        'cadence': 'after_event',
        'channel': 'portal',
        'timing': '7d',
    },
]


def seed_notification_type_settings(apps, schema_editor):
    NotificationTypeSetting = apps.get_model('users', 'NotificationTypeSetting')
    for default in DEFAULT_NOTIFICATION_TYPE_SETTINGS:
        NotificationTypeSetting.objects.get_or_create(
            key=default['key'],
            defaults={
                **default,
                'enabled': True,
                'is_system': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('before_event', 'Before event'), ('after_event', 'After event'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=30)),
                ('channel', models.CharField(choices=[('portal', 'Portal'), ('email', 'Email'), ('portal_email', 'Portal + Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='portal', max_length=30)),
                ('timing', models.CharField(default='08:00', max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_notification_type_settings, migrations.RunPython.noop),
    ]
