# Generated by Django 5.0.3 on 2026-06-20 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reference_numbers(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.order_by('user_id'):
        profile.reference_number = f"MM-{profile.user_id:06d}"
        profile.save(update_fields=['reference_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_theme_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(backfill_reference_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
