# Generated by Django 5.0.3 on 2026-06-20 10:06

from django.db import migrations, models


def mark_existing_active_profiles_verified(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(is_active=True).update(is_phone_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appointment_created_by_userprofile_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_active_profiles_verified, migrations.RunPython.noop),
    ]
