# Generated by Django 5.0.3 on 2026-06-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_facility_coordinates'),
        ('users', '0012_userprofile_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='locations.facility'),
        ),
    ]
