from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.portal_home, name='portal_home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('verify-account/', views.verify_account_view, name='verify_account'),
    path('change-password/', views.password_change_required, name='password_change_required'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            subject_template_name='users/password_reset_subject.txt',
            success_url='/users/password-reset/done/',
        ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/users/reset/done/',
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete',
    ),
    path('logout/', views.logout_view, name='logout'),
    path('auto-logout/', views.auto_logout_view, name='auto_logout'),
    path('session/status/', views.session_status, name='session_status'),
    path('theme/', views.update_theme, name='update_theme'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('journey/', views.my_journey, name='my_journey'),
    path('manage/', views.user_list, name='user_list'),
    path('manage/stats/', views.user_management_stats, name='user_management_stats'),
    path('manage/rows/', views.user_management_rows, name='user_management_rows'),
    path('population-groups/', views.population_group_management, name='population_group_management'),
    path('population-groups/<int:pk>/edit/', views.population_group_edit, name='population_group_edit'),
    path('population-groups/<int:pk>/delete/', views.population_group_delete, name='population_group_delete'),
    path('clients/', views.client_management, name='client_management'),
    path('referrals/analytics/', views.referral_analytics, name='referral_analytics'),
    path('referrals/<str:referral_code>/', views.referral_detail, name='referral_detail'),
    path('referrals/<str:referral_code>/scan/', views.referral_scan, name='referral_scan'),
    path('referrals/<str:referral_code>/slip/', views.referral_slip, name='referral_slip'),
    path('referrals/<str:referral_code>/confirm/', views.referral_confirm, name='referral_confirm'),
    path('clients/<int:pk>/', views.client_record, name='client_record'),
    path('clients/<int:pk>/bulk/<str:kind>/', views.client_bulk_upload_validate, name='client_bulk_upload'),
    path('clients/<int:pk>/bulk/<str:kind>/template/', views.client_bulk_upload_template, name='client_bulk_upload_template'),
    path('clients/<int:pk>/bulk/<str:kind>/commit/', views.client_bulk_upload_commit, name='client_bulk_upload_commit'),
    path('history/<str:app_label>/<str:model_name>/<str:object_pk>/events/', views.object_history_events, name='object_history_events'),
    path('appointments/', views.appointment_list, name='appointment_list'),
    path('appointments/<int:pk>/edit/', views.appointment_edit, name='appointment_edit'),
    path('appointments/<int:pk>/status/', views.appointment_update_status, name='appointment_update_status'),
    path('safeguarding/report/', views.safeguarding_report, name='safeguarding_report'),
    path('safeguarding/cases/', views.safeguarding_management, name='safeguarding_management'),
    path('safeguarding/cases/<int:pk>/', views.safeguarding_case_detail, name='safeguarding_case_detail'),
    path('grievances/submit/', views.grievance_submit, name='grievance_submit'),
    path('grievances/cases/', views.grievance_management, name='grievance_management'),
    path('grievances/cases/<int:pk>/', views.grievance_case_detail, name='grievance_case_detail'),
    path('exit-interview/', views.client_exit_interview, name='client_exit_interview'),
    path('exit-interviews/dashboard/', views.exit_interview_dashboard, name='exit_interview_dashboard'),
    path('create/', views.user_create, name='user_create'),
    path('<int:pk>/', views.user_detail, name='user_detail'),
    path('<int:pk>/profile/', views.user_profile_update, name='user_profile_update'),
    path('<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('<int:pk>/reset-password/', views.user_reset_password, name='user_reset_password'),
    path('<int:pk>/delete/', views.user_delete, name='user_delete'),
]
