spring:
  datasource:
    url: 'jdbc:postgresql://hapi-db:5432/hapi'
    username: hapi
    password: ${HAPI_POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

hapi:
  fhir:
    fhir_version: R5
    tester:
      - id: home
        name: MyMoyo HAPI FHIR
        server_address: 'http://localhost:7201/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R5
