# Generated by Django 5.0.3 on 2026-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRResourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=64)),
                ('logical_id', models.CharField(max_length=128)),
                ('version_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('source_app', models.CharField(max_length=100)),
                ('source_model', models.CharField(max_length=100)),
                ('source_pk', models.CharField(max_length=255)),
                ('resource', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['resource_type', 'logical_id', '-version_id'],
                'indexes': [models.Index(fields=['resource_type', 'logical_id'], name='api_fhirres_resourc_a84c7d_idx'), models.Index(fields=['source_app', 'source_model', 'source_pk'], name='api_fhirres_source__57ac1b_idx'), models.Index(fields=['recorded_at'], name='api_fhirres_recorde_fa61ef_idx')],
                'unique_together': {('resource_type', 'logical_id', 'version_id')},
            },
        ),
    ]
